/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
 
/**
 *
 * @author Microsoft
 */
public class Databuku extends javax.swing.JFrame {
Connection conn=null;
Statement st=null;
    /**
     * Creates new form Databuku
     */ Connection con = Koneksidb.getkoneksi();
    public Databuku() {
        initComponents();
        tampil_buku();
    }
   private void tampil_buku(){
     // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id_buku");
        model.addColumn("Judul_buku");
        model.addColumn("nomor_buku");
        model.addColumn("Pengarang");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Penerbit");
        model.addColumn("Kategori");
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT * FROM `data_buku`";
            java.sql.Statement s=con.createStatement();
            java.sql.ResultSet res=s.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)
                               ,res.getString(6),res.getString(7),res.getString(8)});
            }
            Tabelbuku.setModel(model);
        } catch (Exception e) {
        }
    }
     private void reset(){
        txtNobuku.setText("");
        IsiidBuku.setText("");
        IsijudulBuku.setText("");
        Isipengarang.setText("");
        Isistok.setText("");
        Isistok.setText("");
        Isiharga.setText(""); 
        Isipenerbit.setText(""); 
        Isipilih.setSelectedItem(""); 
     }
   private void cari(){
        //menampilkan data database kedalam tabel
         // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id_buku");
        model.addColumn("Judul_buku");
        model.addColumn("nomor_buku");
        model.addColumn("Pengarang");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Penerbit");
        model.addColumn("Kategori");
        try {
            String cari = Txtcari.getText();
            String sql = "select * from data_buku where Kategori like '%"+cari+"%'";
            java.sql.Statement se=con.createStatement();
            java.sql.ResultSet res=se.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)
                               ,res.getString(6),res.getString(7),res.getString(8)});
            }
            Tabelbuku.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }
   public void tampil_kategori()
    {
        try
        {
            String sql = "select * from Kategori";
            java.sql.Statement st=conn.createStatement();
            java.sql.ResultSet re=st.executeQuery(sql);
            Isipilih.addItem("-Pilih Kategori buku");
            while(re.next())
            {
                Isipilih.addItem(re.getString("nama_kategori"));
            }
        }
        catch(Exception ex)
        {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelbuku = new javax.swing.JTable();
        IsiidBuku = new javax.swing.JTextField();
        IsijudulBuku = new javax.swing.JTextField();
        Isipengarang = new javax.swing.JTextField();
        Isistok = new javax.swing.JTextField();
        Isiharga = new javax.swing.JTextField();
        Isipenerbit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txtcari = new javax.swing.JTextField();
        btnRst = new javax.swing.JButton();
        btnSpn = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        txtNobuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Isipilih = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 219, 138));

        Tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "nomor_buku", "Judul_buku", "Id_buku", "Pengarang", "Stok", "Harga", "Penerbit", "Kategori"
            }
        ));
        Tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabelbuku);

        IsiidBuku.setBackground(new java.awt.Color(233, 229, 154));

        IsijudulBuku.setBackground(new java.awt.Color(233, 229, 154));

        Isipengarang.setBackground(new java.awt.Color(233, 229, 154));
        Isipengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsipengarangActionPerformed(evt);
            }
        });

        Isistok.setBackground(new java.awt.Color(233, 229, 154));

        Isiharga.setBackground(new java.awt.Color(233, 229, 154));

        Isipenerbit.setBackground(new java.awt.Color(233, 229, 154));

        jLabel1.setText("Id_Buku");

        jLabel2.setText("Judul_Buku");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Stok");

        jLabel5.setText("Penerbit");

        jLabel6.setText("Harga");

        Txtcari.setBackground(new java.awt.Color(233, 229, 154));

        btnRst.setText("Reset");
        btnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstActionPerformed(evt);
            }
        });

        btnSpn.setText("Simpan");
        btnSpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSpnMouseClicked(evt);
            }
        });
        btnSpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpnActionPerformed(evt);
            }
        });

        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        txtNobuku.setBackground(new java.awt.Color(233, 229, 154));

        jLabel7.setText("Nomor");

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyConnection/open-book.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyConnection/back_1.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel10.setText("Kategori");

        Isipilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "Teknologi", "Cerita Dongeng", "Sains", "Makanan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(btnCari)))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSpn)
                                .addGap(24, 24, 24)
                                .addComponent(btnRst, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(IsiidBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNobuku, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel4)
                                                .addGap(30, 30, 30))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Isistok, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Isiharga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IsijudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Isipenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Isipengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Isipilih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 111, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNobuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Isistok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiidBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCari)
                        .addGap(22, 22, 22)
                        .addComponent(Txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IsijudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(Isipenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isipengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(Isipilih, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus)
                        .addComponent(btnUbah)
                        .addComponent(btnRst)
                        .addComponent(btnSpn))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsipengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsipengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsipengarangActionPerformed

    private void TabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelbukuMouseClicked
        // TODO add your handling code here:
        int row = Tabelbuku.getSelectedRow();
       txtNobuku.setText(Tabelbuku.getModel().getValueAt(row, 0).toString());
       IsiidBuku.setText(Tabelbuku.getModel().getValueAt(row, 1).toString());
       IsijudulBuku.setText(Tabelbuku.getModel().getValueAt(row, 2).toString());
       Isipengarang.setText(Tabelbuku.getModel().getValueAt(row, 3).toString());
       Isistok.setText(Tabelbuku.getModel().getValueAt(row, 4).toString());
       Isiharga.setText(Tabelbuku.getModel().getValueAt(row, 5).toString());
       Isipenerbit.setText(Tabelbuku.getModel().getValueAt(row, 6).toString());
       Isipilih.setSelectedItem(Tabelbuku.getModel().getValueAt(row, 7).toString());
       // txtkategori.setSelectedItem(tabelbuku.getModel().getValueAt(row, 6).toString());
       
    }//GEN-LAST:event_TabelbukuMouseClicked

    private void btnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnRstActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpnActionPerformed

    }//GEN-LAST:event_btnSpnActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            if(Tabelbuku.getSelectedRowCount()==0){
                JOptionPane.showMessageDialog(null,"Silahkan pilih baris data yang akan di ubah");
                return ;
            }else{
               String sql="UPDATE data_buku SET Id_buku='"+IsiidBuku.getText()+"',Judul_buku='"+IsijudulBuku.getText()+"',Pengarang='"+Isipengarang.getText()+"',"
                        + "Stok='"+Isistok.getText()+"',Harga='"+ Isiharga.getText()+"',Penerbit='"+Isipenerbit.getText()+"',Kategori='"+Isipilih.getSelectedItem()+"' WHERE nomor_buku='"+txtNobuku.getText()+"'";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_buku();
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpnMouseClicked
        // TODO add your handling code here:
         if((txtNobuku.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Nomor Buku Tidak Boleh Kosong ");
        }else if((IsiidBuku.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Pengarang masih kosong mohon di isi");
        }else if((IsijudulBuku.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Judul Buku Tidak Boleh Kosong");
        }else if((Isipengarang.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Pengarang masih kosong mohon di isi");
        }else if((Isistok.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "penerbit masih kosong mohon di isi");
        }else if((Isiharga.getText().equals(""))){
            JOptionPane.showMessageDialog(null, " Harga masih kosong mohon di isi");
        }else if((Isipenerbit.getText().equals(""))){
            JOptionPane.showMessageDialog(null, " stok masih kosong silahkan isi terlebih dahulu");
        }else if((Isipilih.getSelectedItem().equals(""))){
            JOptionPane.showMessageDialog(null, " Kategori belum di pilih silahakan pilih kategori buku");
        }  
            else{
                  
        }
        
        String nomor_buku = txtNobuku.getText();    
        String Id_buku = IsiidBuku.getText();
        String Judul_buku = IsijudulBuku.getText();
        String Pengarang= Isipengarang.getText();
        String Stok = Isistok.getText();
        String Harga= Isiharga.getText();
        String Penerbit = Isipenerbit.getText();
        String Kategori = (String) Isipilih.getSelectedItem();
            try {
                Connection con= Koneksidb.getkoneksi();
                String sql = "INSERT INTO data_buku VALUES (?,?,?,?,?,?,?,? )";
                PreparedStatement pe = con.prepareStatement(sql);
                    
                    pe.setString(1, nomor_buku);
                    pe.setString(2, Id_buku);
                    pe.setString(3, Judul_buku);
                    pe.setString(4, Pengarang);
                    pe.setString(5, Stok);
                    pe.setString(6, Harga);
                    pe.setString(7, Penerbit);
                    pe.setString(8, Kategori);
                    pe.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
                tampil_buku();
                reset();
            }catch(SQLException ex){
                System.out.println("erur");
            }
        
    }//GEN-LAST:event_btnSpnMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
         if(Tabelbuku.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null,"Silahkan pilih baris data yang akan di ubah");
            return ;
        }
        if(JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Menghapus ini?")==JOptionPane.OK_OPTION){
            try{

                String sql="DELETE FROM data_buku WHERE nomor_buku='"+txtNobuku.getText()+"'";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data anda berhasil di hapus");
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampil_buku();
            reset();
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         Dashboardutama x = new Dashboardutama();
                x.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Databuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Isiharga;
    private javax.swing.JTextField IsiidBuku;
    private javax.swing.JTextField IsijudulBuku;
    private javax.swing.JTextField Isipenerbit;
    private javax.swing.JTextField Isipengarang;
    private javax.swing.JComboBox<String> Isipilih;
    private javax.swing.JTextField Isistok;
    private javax.swing.JTable Tabelbuku;
    private javax.swing.JTextField Txtcari;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRst;
    private javax.swing.JButton btnSpn;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNobuku;
    // End of variables declaration//GEN-END:variables
}
