/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Microsoft
 */
public class FormRegister extends javax.swing.JFrame {
Connection conn=null;
Statement st=null;
    /**
     * Creates new form FormRegister
     */
    public FormRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fieldname = new javax.swing.JTextField();
        Femail = new javax.swing.JTextField();
        Fhp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        FkonPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 188, 121));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 243, 31));
        jPanel1.add(Femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 243, 31));
        jPanel1.add(Fhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 243, 31));

        jLabel2.setBackground(new java.awt.Color(201, 188, 121));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No Handphone :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
        jPanel1.add(Fpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 243, 33));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 116, -1));
        jPanel1.add(FkonPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 243, 33));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Konfirmasi Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(201, 188, 121));
        jButton1.setText("Register");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 101, 40));

        jLabel7.setText("Sudah memiliki akun?  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jLabel8.setText("LOGIN");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 83, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyConnection/Register.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 832, 526));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (Fieldname.getText().equals("")){
            JOptionPane.showMessageDialog(null," isi sername Anda terlebih dahulu");
            Fieldname.requestFocus();
        }
        else if(Fhp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"isi No Hp anda");
            Fhp.requestFocus();            
        }
        else if(Femail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"isi email anda!");
            Femail.requestFocus();            
        }
        else if(Fpass.getText().equals("")){
            JOptionPane.showMessageDialog(null,"masukkan password");
            Fpass.requestFocus();            
        }
        else if(FkonPass.getText().equals("")){
            JOptionPane.showMessageDialog(null,"konfirmasi password");
            FkonPass.requestFocus();
        }
        else{
            
        }
        String email = Femail.getText();
        String username = Fieldname.getText();
        String Password = String.valueOf(Fpass.getPassword());
        String konfirmasipassword = String.valueOf(FkonPass.getPassword());
        String nohp = Fhp.getText();
        
        if (!Password.equals(konfirmasipassword)){
            JOptionPane.showMessageDialog(null, "Password Anda Salah");    
        }else if (Password.equals("")|| username.equals("")){
            JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");
        }else{
            try{
                Connection con = Koneksidb.getkoneksi();
                String sql = "INSERT INTO login VALUES (?, ?, ?, ?, ? )";
                PreparedStatement pe = con.prepareStatement(sql);
                
                    pe.setString(1, username);
                    pe.setString(2, Password);
                    pe.setString(3, konfirmasipassword);
                    pe.setString(4, nohp);
                    pe.setString(5, email);
                    pe.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Berhasil Membuat Akun");
            }catch(SQLException ex){
                System.out.println("erur");
            }finally{
                this.dispose();
                new Formlogin().show();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          Formlogin x = new Formlogin();
                x.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked
       
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Femail;
    private javax.swing.JTextField Fhp;
    private javax.swing.JTextField Fieldname;
    private javax.swing.JPasswordField FkonPass;
    private javax.swing.JPasswordField Fpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
