/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Microsoft
 */
public class Kasir extends javax.swing.JFrame {
Connection conn=null;
Statement st=null;
    /**
     * Creates new form Kasir
     */Connection con = Koneksidb.getkoneksi();
    public Kasir() {
        initComponents();
        tampil_kasir();
    }
 private void tampil_kasir(){
     // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id_pegawai");
        model.addColumn("Nama");
        model.addColumn("NoHp");
        model.addColumn("Alamat");
       
       
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT * FROM `pegawai`";
            java.sql.Statement st=con.createStatement();
            java.sql.ResultSet re=st.executeQuery(sql);
            while(re.next()){
            model.addRow(new Object[]{re.getString(1),re.getString(2),re.getString(3),re.getString(4)});
            }
            Tabelkasir.setModel(model);
        } catch (Exception e) {
        }
    }
 private void reset(){
        Isiidpgw.setText("");
        Isinama.setText("");
        IsinoHp.setText("");
        Isialamat.setText("");
     }
   private void cari(){
        //menampilkan data database kedalam tabel
         // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id_pegawai");
        model.addColumn("Nama");
        model.addColumn("NoHp");
        model.addColumn("Alamat");
        try {
            String cari = btnCari.getText();
            String sql = "select * from pegawai where nama LIKE '%"+cari+"%'";
            java.sql.Statement se=conn.createStatement();
            java.sql.ResultSet res=se.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)
                               ,res.getString(6),res.getString(7)});
            }
            Tabelkasir.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabelkasir = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Isiidpgw = new javax.swing.JTextField();
        Isinama = new javax.swing.JTextField();
        IsinoHp = new javax.swing.JTextField();
        Isialamat = new javax.swing.JTextField();
        btnHps = new javax.swing.JButton();
        btnSpn = new javax.swing.JButton();
        btnRst = new javax.swing.JButton();
        Txtcari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 202, 125));

        Tabelkasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_pegawai", "Nama", "No Hp", "Alamat"
            }
        ));
        Tabelkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelkasirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabelkasir);

        jLabel1.setText("Id_pegawai");

        jLabel2.setText("Nama");

        jLabel3.setText("No Hp");

        jLabel4.setText("Alamat");

        IsinoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsinoHpActionPerformed(evt);
            }
        });

        btnHps.setText("Hapus");
        btnHps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHpsMouseClicked(evt);
            }
        });

        btnSpn.setText("Simpan");
        btnSpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSpnMouseClicked(evt);
            }
        });

        btnRst.setText("Reset");
        btnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyConnection/back_1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHps, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnSpn)
                        .addGap(32, 32, 32)
                        .addComponent(btnRst, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(IsinoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(Isialamat, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Isinama, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Isiidpgw, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Isiidpgw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(IsinoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isialamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRst)
                            .addComponent(btnSpn)
                            .addComponent(btnHps))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsinoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsinoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsinoHpActionPerformed

    private void TabelkasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelkasirMouseClicked
        // TODO add your handling code here:
           int row = Tabelkasir.getSelectedRow();
       Isiidpgw.setText(Tabelkasir.getModel().getValueAt(row, 0).toString());
       Isinama.setText(Tabelkasir.getModel().getValueAt(row, 1).toString());
       IsinoHp.setText(Tabelkasir.getModel().getValueAt(row, 2).toString());
       Isialamat.setText(Tabelkasir.getModel().getValueAt(row, 3).toString());
       
    }//GEN-LAST:event_TabelkasirMouseClicked

    private void btnSpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpnMouseClicked
        // TODO add your handling code here:
         if((Isiidpgw.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Id pegawai Tidak Boleh Kosong ");
        }else if((Isinama.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
        }else if((IsinoHp.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "No Hp kosong mohon di isi");
        }else if((Isialamat.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Alamat masih kosong mohon di isi");
        }
        else{
            
        }
        String Id_pegawai= Isiidpgw.getText();    
        String Nama = Isinama.getText();
        String  NoHp= IsinoHp.getText();
        String Alamat= Isialamat.getText();
   
        
            try {
                Connection con= Koneksidb.getkoneksi();
                String sql = "INSERT INTO pegawai VALUES (?,?,?,?)";
                PreparedStatement pe = con.prepareStatement(sql);
                    
                    pe.setString(1, Id_pegawai);
                    pe.setString(2, Nama);
                    pe.setString(3, NoHp);
                    pe.setString(4, Alamat);
                    pe.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
                tampil_kasir();
                reset();
            }catch(SQLException ex){
                System.out.println("erur");
            }
        
    }//GEN-LAST:event_btnSpnMouseClicked

    private void btnHpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHpsMouseClicked
        // TODO add your handling code here:
           if(Tabelkasir.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null,"Silahkan pilih baris data yang akan di ubah");
            return ;
        }
        if(JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Menghapus ini?")==JOptionPane.OK_OPTION){
            try{

                String sql="DELETE FROM pegawai WHERE Id_pegawai='"+Isiidpgw.getText()+"'";
                PreparedStatement pst=conn.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data anda berhasil di hapus");
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampil_kasir();
            reset();
        }
    }//GEN-LAST:event_btnHpsMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Dashboardutama x = new Dashboardutama();
                x.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnRstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
         } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Isialamat;
    private javax.swing.JTextField Isiidpgw;
    private javax.swing.JTextField Isinama;
    private javax.swing.JTextField IsinoHp;
    private javax.swing.JTable Tabelkasir;
    private javax.swing.JTextField Txtcari;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHps;
    private javax.swing.JButton btnRst;
    private javax.swing.JButton btnSpn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
